AllCops:
  TargetRubyVersion: 2.7.0
  Exclude:
    - '/**/db/schema.rb'
    - '/**/bin/bundle'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - '/**/spec/support/schemas/**/*'
    - '/**/db/migrate/**/*'
    - '/**/config/initializers/**/*'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - '/**/db/migrate/**/*'
    - '/**/config/initializers/**/*'

Style/ClassVars:
  Enabled: false

Metrics/ParameterLists:
  Max: 8

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - '/**/config/environments/*'
    - 'spec/**/*'
